from enum import StrEnum

class EmailCategory(StrEnum):
    """Enum for email categories."""
    APPLICATION_SUBMISSION = "APPLICATION_SUBMISSION"
    JOB_INTERVIEW = "JOB_INTERVIEW"
    INTERVIEW_CONFIRMATION = "INTERVIEW_CONFIRMATION"
    
    REJECTION = "REJECTION"
    APPLICATION_UPDATE = "APPLICATION_UPDATE"
    ASSESSMENT = "ASSESSMENT"
    OFFER = "OFFER"
    
    FOLLOW_UP_NEEDED = "FOLLOW_UP_NEEDED"
    
    UNRECOGNIZED = "UNRECOGNIZED"
    NOT_JOB_RELATED = "NOT_JOB_RELATED"
    
    INITIAL_RECRUITER_OUTREACH = "INITIAL_RECRUITER_OUTREACH"
    RECRUITER_FOLLOW_UP = "RECRUITER_FOLLOW_UP"